// <auto-generated />
using System;
using AlxorCore.Facturacion.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Facturacion.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(FacturacionDbContext))]
    [Migration("20260826104620_FacturaObservaciones")]
    partial class FacturaObservaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facturacion")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("ClienteCalle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_calle");

                    b.Property<string>("ClienteCodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cliente_cp");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_nif");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<string>("ClientePoblacion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cliente_poblacion");

                    b.Property<string>("ClienteProvincia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cliente_provincia");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoEnvioAeat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_envio_aeat");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTimeOffset?>("FechaHoraGenRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora_gen_registro");

                    b.Property<DateOnly>("FechaOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_operacion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("Huella")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("huella");

                    b.Property<string>("HuellaAnterior")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("huella_anterior");

                    b.Property<string>("IdRegistro")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_registro");

                    b.Property<string>("MotivoRectificacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_rectificacion");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("NumeroCompleto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_completo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pais");

                    b.Property<decimal>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo");

                    b.Property<bool>("RecargoEquivalencia")
                        .HasColumnType("boolean")
                        .HasColumnName("recargo_equivalencia");

                    b.Property<decimal>("RecargoTotal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("recargo_total");

                    b.Property<Guid?>("RectificaFacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rectifica_factura_id");

                    b.Property<decimal>("RetencionIrpf")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("retencion_irpf");

                    b.Property<string>("TipoFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_factura");

                    b.Property<string>("TipoOperacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_operacion");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Prefijo", "Ejercicio", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_factura_numero");

                    b.ToTable("factura", "facturacion");
                });

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.FacturaRecurrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("FacturasGeneradas")
                        .HasColumnType("integer")
                        .HasColumnName("facturas_generadas");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodicidad");

                    b.Property<decimal>("PorcentajeIrpf")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_irpf");

                    b.Property<DateOnly>("ProximaEmision")
                        .HasColumnType("date")
                        .HasColumnName("proxima_emision");

                    b.Property<DateOnly?>("UltimaEmision")
                        .HasColumnType("date")
                        .HasColumnName("ultima_emision");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Activa", "ProximaEmision")
                        .HasDatabaseName("ix_recurrente_vencidas");

                    b.ToTable("factura_recurrente", "facturacion");
                });

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.Presupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("NumeroCompleto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_completo");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.Property<DateOnly>("Validez")
                        .HasColumnType("date")
                        .HasColumnName("validez");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_presupuesto_empresa_fecha");

                    b.ToTable("presupuesto", "facturacion");
                });

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.Factura", b =>
                {
                    b.OwnsMany("AlxorCore.Facturacion.Dominio.LineaFactura", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("CodigoIva")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("codigo_iva");

                            b1.Property<decimal>("CosteUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("coste_unitario");

                            b1.Property<decimal>("CuotaIva")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_iva");

                            b1.Property<decimal>("CuotaRecargo")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_recargo");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("descuento");

                            b1.Property<decimal>("PorcentajeIva")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_iva");

                            b1.Property<decimal>("PorcentajeRecargo")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_recargo");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("factura_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("factura_id");

                            b1.ToTable("linea_factura", "facturacion");

                            b1.WithOwner()
                                .HasForeignKey("factura_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.FacturaRecurrente", b =>
                {
                    b.OwnsMany("AlxorCore.Facturacion.Dominio.LineaRecurrente", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("CodigoIva")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("codigo_iva");

                            b1.Property<decimal>("CuotaIva")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_iva");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("descuento");

                            b1.Property<decimal>("PorcentajeIva")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_iva");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("factura_recurrente_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("factura_recurrente_id");

                            b1.ToTable("linea_recurrente", "facturacion");

                            b1.WithOwner()
                                .HasForeignKey("factura_recurrente_id");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Facturacion.Dominio.Presupuesto", b =>
                {
                    b.OwnsMany("AlxorCore.Facturacion.Dominio.LineaPresupuesto", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("CodigoIva")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("codigo_iva");

                            b1.Property<decimal>("CuotaIva")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_iva");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("descuento");

                            b1.Property<decimal>("PorcentajeIva")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_iva");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid?>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.Property<Guid>("presupuesto_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("presupuesto_id");

                            b1.ToTable("linea_presupuesto", "facturacion");

                            b1.WithOwner()
                                .HasForeignKey("presupuesto_id");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
