// <auto-generated />
using System;
using AlxorCore.Terceros.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Terceros.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(TercerosDbContext))]
    [Migration("20260826170335_AgregarTelefonoCliente")]
    partial class AgregarTelefonoCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("terceros")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Terceros.Dominio.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("iban");

                    b.Property<DateOnly?>("MandatoFecha")
                        .HasColumnType("date")
                        .HasColumnName("mandato_fecha");

                    b.Property<string>("MandatoReferencia")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("mandato_referencia");

                    b.Property<string>("NifFiscal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif_fiscal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeIrpfDefecto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("irpf_defecto");

                    b.Property<bool>("RecargoEquivalencia")
                        .HasColumnType("boolean")
                        .HasColumnName("recargo_equivalencia");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_cliente_empresa_nombre");

                    b.ToTable("cliente", "terceros");
                });

            modelBuilder.Entity("AlxorCore.Terceros.Dominio.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pago");

                    b.Property<string>("NifFiscal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif_fiscal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeIrpfDefecto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("irpf_defecto");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_proveedor_empresa_nombre");

                    b.ToTable("proveedor", "terceros");
                });

            modelBuilder.Entity("AlxorCore.Terceros.Dominio.Cliente", b =>
                {
                    b.OwnsOne("AlxorCore.Nucleo.Comun.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("direccion_cp");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_poblacion");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_provincia");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente", "terceros");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("AlxorCore.Terceros.Dominio.Proveedor", b =>
                {
                    b.OwnsOne("AlxorCore.Nucleo.Comun.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("direccion_cp");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_poblacion");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("direccion_provincia");

                            b1.HasKey("ProveedorId");

                            b1.ToTable("proveedor", "terceros");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
