<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AlxorCore.Api</RootNamespace>
    <AssemblyName>AlxorCore.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Identidad\AlxorCore.Identidad.csproj" />
    <ProjectReference Include="..\AlxorCore.Identidad.Infraestructura\AlxorCore.Identidad.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Organizacion\AlxorCore.Organizacion.csproj" />
    <ProjectReference Include="..\AlxorCore.Organizacion.Infraestructura\AlxorCore.Organizacion.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Terceros\AlxorCore.Terceros.csproj" />
    <ProjectReference Include="..\AlxorCore.Terceros.Infraestructura\AlxorCore.Terceros.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Clinica\AlxorCore.Clinica.csproj" />
    <ProjectReference Include="..\AlxorCore.Clinica.Infraestructura\AlxorCore.Clinica.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Catalogo\AlxorCore.Catalogo.csproj" />
    <ProjectReference Include="..\AlxorCore.Catalogo.Infraestructura\AlxorCore.Catalogo.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Facturacion\AlxorCore.Facturacion.csproj" />
    <ProjectReference Include="..\AlxorCore.Facturacion.Infraestructura\AlxorCore.Facturacion.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Gastos\AlxorCore.Gastos.csproj" />
    <ProjectReference Include="..\AlxorCore.Gastos.Infraestructura\AlxorCore.Gastos.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Tesoreria\AlxorCore.Tesoreria.csproj" />
    <ProjectReference Include="..\AlxorCore.Tesoreria.Infraestructura\AlxorCore.Tesoreria.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Documentos\AlxorCore.Documentos.csproj" />
    <ProjectReference Include="..\AlxorCore.Documentos.Infraestructura\AlxorCore.Documentos.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Informes\AlxorCore.Informes.csproj" />
    <ProjectReference Include="..\AlxorCore.Informes.Infraestructura\AlxorCore.Informes.Infraestructura.csproj" />
    <ProjectReference Include="..\AlxorCore.Auditoria\AlxorCore.Auditoria.csproj" />
    <ProjectReference Include="..\AlxorCore.Auditoria.Infraestructura\AlxorCore.Auditoria.Infraestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

</Project>
