<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlxorCore.Clinica.Infraestructura</RootNamespace>
    <AssemblyName>AlxorCore.Clinica.Infraestructura</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Persistencia\AlxorCore.Persistencia.csproj" />
    <ProjectReference Include="..\AlxorCore.Clinica\AlxorCore.Clinica.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
