// <auto-generated />
using System;
using AlxorCore.Clinica.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Clinica.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20260814083918_AgregarActosClinicos")]
    partial class AgregarActosClinicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clinica")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.ActoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset?>("CobradoTicketEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cobrado_ticket_en");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("importe");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_iva");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia_tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_acto_clinico_empresa_animal");

                    b.HasIndex("EmpresaId", "ClienteId", "Estado")
                        .HasDatabaseName("ix_acto_clinico_empresa_cliente_estado");

                    b.ToTable("acto_clinico", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especie");

                    b.Property<bool>("Esterilizado")
                        .HasColumnType("boolean")
                        .HasColumnName("esterilizado");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Microchip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("microchip");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notas");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("peso_kg");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ClienteId")
                        .HasDatabaseName("ix_animal_empresa_cliente");

                    b.ToTable("animal", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Cirugia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Anestesia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("anestesia");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<string>("Cirujano")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cirujano");

                    b.Property<string>("Complicaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("complicaciones");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateOnly?>("ProximaRevision")
                        .HasColumnType("date")
                        .HasColumnName("proxima_revision");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_cirugia_empresa_animal");

                    b.HasIndex("EmpresaId", "ProximaRevision")
                        .HasDatabaseName("ix_cirugia_empresa_proxima_revision");

                    b.ToTable("cirugia", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("veterinario");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_cita_empresa_animal");

                    b.HasIndex("EmpresaId", "Inicio")
                        .HasDatabaseName("ix_cita_empresa_inicio");

                    b.HasIndex("EmpresaId", "Estado", "Inicio")
                        .HasDatabaseName("ix_cita_empresa_estado_inicio");

                    b.ToTable("cita", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("diagnostico");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("peso_kg");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tratamiento");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("veterinario");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_consulta_empresa_animal");

                    b.ToTable("consulta", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.PautaVacunal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Caracter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("caracter");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int?>("EdadInicioSemanas")
                        .HasColumnType("integer")
                        .HasColumnName("edad_inicio_semanas");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PeriodicidadRefuerzoMeses")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidad_refuerzo_meses");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Especie", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_pauta_vacunal_empresa_especie_nombre");

                    b.ToTable("pauta_vacunal", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Recordatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateOnly>("FechaObjetivo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_objetivo");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notas");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia_tipo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_recordatorio_empresa_animal");

                    b.HasIndex("EmpresaId", "Estado", "FechaObjetivo")
                        .HasDatabaseName("ix_recordatorio_empresa_estado_fecha");

                    b.HasIndex("EmpresaId", "ReferenciaTipo", "ReferenciaId")
                        .IsUnique()
                        .HasDatabaseName("ix_recordatorio_referencia")
                        .HasFilter("referencia_id IS NOT NULL");

                    b.ToTable("recordatorio", "clinica");
                });

            modelBuilder.Entity("AlxorCore.Clinica.Dominio.Vacunacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("FechaAplicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_aplicacion");

                    b.Property<string>("Lote")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("lote");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notas");

                    b.Property<Guid?>("PautaVacunalId")
                        .HasColumnType("uuid")
                        .HasColumnName("pauta_vacunal_id");

                    b.Property<DateOnly?>("ProximaDosis")
                        .HasColumnType("date")
                        .HasColumnName("proxima_dosis");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("veterinario");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AnimalId")
                        .HasDatabaseName("ix_vacunacion_empresa_animal");

                    b.HasIndex("EmpresaId", "ProximaDosis")
                        .HasDatabaseName("ix_vacunacion_empresa_proxima_dosis");

                    b.ToTable("vacunacion", "clinica");
                });
#pragma warning restore 612, 618
        }
    }
}
